Module2 task1
htmlacademy-adaptive/2426581-cat-energy-1 pull request #3
Opened 2024-06-12 07:59 UTC by Roman3723

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +        <a class="main-header__logo-text" href="#">
Думаешь, что это два разных элемента?

Вообще, логотип это явный блок. Ты его два раза переиспользуешь в шапке и потом ещё в футере. 
А потом ещё неизвестно сколько раз на других ресурсах компании, а также глобально на всех (или близко к тому) разработанных тобой сайтах. 

И модификаторы.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +          <input class="burger-checkbox" type="checkbox" id="burger-checkbox">
Меню открывается кнопкой. 
input - элемент ввода данных через форму.

И тебе будет удобнее, если он будет блоком. Взял разметку, стили и понес на другие сайты, чуть поменял стили под новый макет и готово.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +            <!--! Q не блокирует ли враппер действие кнопки бургер на список меню?-->
Этот div просто лишний. 
Или расскажи, что ты хочешь с его помощью делать.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
>    </head>
Сервис для проверки корректности БЭМ 
https://yoksel.github.io/html-tree/
Нужно проверить все страницы.
Если не понятно почему он недоволен - спрашивай.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +                <a href="#">главная</a>
Мы знаем адрес главной страницы и можем указать его в href

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +              <li class="list__item list__item--active">
Лучше `--current`, понятнее

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +              <li class="list__item"><a href="form.html">
Форматирование лучше единообразное, лесенкой. 
Чем раньше привыкнешь к кодгайду Академии, тем будет легче.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +        <a class="hero__button button--green" href="#">подобрать программу</a>
`--green`
Если кнопка станет красной, то придется бегать менять не только цвет, но и класс. 

Есть слова brand, accent, bright и т.д. Они универсальны и можно спокойно менять зеленый на какой угодно.

Да, в изначальном варианте БЭМ модификаторы писались через `_`. Но такая запись не так хорошо читается и большинство разработчиков предпочитает "европейскую" схему с `--`

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +        <div class="diet-program diet-program--slim">
Да, будет очень странно, если стили для секции и её дочерних элементов будут совпадать. Вряд ли им нужен одинаковый класс. 

`div` по спецификации используется лишь тогда, когда нет подходящих по смыслу тегов. Когда обертка нужна только ради обертки, потому что иначе никак.
В данном случае есть, например, `ul`. Ведь фактически это список программ.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +            вес.</p>
```suggestion
          <p class="diet-program__description">Ваш кот весит больше собаки и
            почти утратил способность лазить по деревьям? Пора на диету!
            Cat Energy Slim поможет вашему питомцу сбросить лишний
            вес.</p>
```
Не надо ставить br раньше времени. Только если без них никак. И лучше пользоваться неразрывными пробелами по правилам типографики, чем переносами. 

br оправданы в больших заголовках для дизайнерских целей, обычные тексты как ложатся в ширину, так и хорошо. 

У нас довольно строгий Pixel Perfect, поэтому, возможно, где-то они понадобятся. Но мы будет стараться обойтись без них.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +          <a class="diet-program__catalog" href="#">каталог slim</a>
```suggestion
          <a class="diet-program__catalog" href="#">каталог Slim</a>
```
Все тексты пишутся по правилам языка страницы. И названия с большой буквы.

Тут и всюду.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +          <h3 class="diet-program__title">похудение</h3>
```suggestion
          <h3 class="diet-program__title">Похудение</h3>
```

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +      </section>
```suggestion
      <section class="advantages"> <!--! Q блок преимуществ?--> 
        <h2 class="advantages__title">Как это работает</h2>
          <ul class="advantages__list advantages__wrapper"> <!-- я бы использовала общий класс container, а не сотню разных с одинаковыми стилями -->
            <li class="advantages__item advantages__item--healthy">
              <!--! Q нужен ли класс-модификатор для картинки?-->
              <!-- а как ты без него будешь их менять? -->
              <!--! Q нужен ли здесь класс advantages__title?-->
              <p class="advantages__description">Функциональное питание
                содержит только полезные
                питательные вещества.</p>
            </li>
            <li class="advantages__item advantages__item--easy">
              <p class="advantages__description">Выпускается в виде порошка,
                который нужно лишь залить
                кипятком и готово.</p>
            </li>
            <li class="advantages__item advantages__item--diet">
              <!--! Q затрудняюсь придумать название заголовку-->
              <!-- Не очень понятно, зачем пользователям скринридеров какая-то дополнительная информация -->
              <p class="advantages__description">Замените один-два приема
                обычной еды на наше
                функциональное питание.</p>
            </li>
            <li class="advantages__item advantages__item--result">
              <p class="advantages__description">Уже через месяц
                наслаждайтесь изменениями к&nbsp;лучшему вашего питомца!</p>
            </li>
          </ul>
      </section>
```

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +        <div class="stats__wrapper slider">
Слайдер разве тут начинается?
Логика слайдера вполне обычная, рычажок меняет картинки до и после похудения. 
Вот первый попавшийся пример https://elfsight.com/ru/before-and-after-slider-widget/ (код оттуда брать не надо)

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +      </section>
```suggestion
            <h2 class="stats__title">Живой пример</h2>
            <p class="stats__text">Борис сбросил 5 кг за 2 месяца, просто
              <br>заменив свой обычный корм на Cat Energy <br>Slim. Отличный
              результат без изнуряющих <br>тренировок! При этом он не менял
              своих <br>привычек и по-прежнему спит по 16 часов <br>в день.
            </p>
          <dl class="stats__wrapper">
            <!--! враппер нужен для стилизации Веса и Времени-->
            <div class="stats__item">
               <dt>снижение веса</dt>
              <dd>5 кг</dd>
            </div>
            <div class="stats__item">
              <dt>затрачено времени</dt>
              <dd>60 дней</b>
            </div>
          </div>
          <div class="stats__item  stats__item--wide">
            <dt>затраты на питание: <dt>
            <dd>15 000 руб.</dd>
          </div>
        </dl>
          <!-- если в общий список тяжело, то затраты на питание можно выделить отдельным параграфом -->
          <img src="img/compare-slider.jpg"
            alt="Борис до и после курса питания.">
          <!-- ЗДЕсь должен быть сверстан слайдер-->
        </div>
      </section>
```

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +          <br>дилеров!</b>
```suggestion
        <p class="contacts__title">приглашаем к сотрудничеству
          дилеров!</p>
```
И тут бы поправить логику.
Ты вроде считаешь этот текст заголовком, даешь ему класс title, но при этом используешь тег `p`. Либо туда либо сюда.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +        <img src="img/location-map.svg" alt="карта района города."
Как она получилась svg? 
Это же касается почти всех растровых картинок в проекте.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +        <div class="main-footer__social social">
Либо секция с заголовком и списком либо эта обертка дивом лишняя.

2024-06-12 11:46 UTC, Ankhena commented on source/index.html
> +        <div class="main-footer__copyright copyright">
Аналогично

2024-06-12 11:46 UTC, Ankhena commented on source/catalog.html
> +          </li>
```suggestion
          <li class="product__item">
              <!--! Q возможно, изображение является ссылкой?-->
              <!-- Именно! Заголовок тоже. А чтобы не табать лишнего с клавиатуры, задаем атрибут tabindex="-1" -->
              <img class="product-card__img" src="img/catalog-1.svg"
                alt="Cat Energy Pro 500 г.">
                <h3>Cat Energy Pro 500 г.</h3>
              <dl class="product-card__info">
                <dt class="product__mass">Масса</dt>
                <dd> 500 г</dd>
                <--  далее аналогично-->
                <span class="product__taste">Вкус Курица</span>
                <br>
                <span class="product__price">Цена 700 р</span>
              </dl>
              <button class="product-card__button button"
                type="button">заказать</button>
          </li>
```

2024-06-12 11:46 UTC, Ankhena commented on source/form.html
> +      <!--! Q не уверен в правильности именования класса секции-->
Да, не очень понятно чей это элемент.

2024-06-12 11:46 UTC, Ankhena commented on source/form.html
> +          <form
Формы обычно переиспользуются, их удобно делать блоками (с модификаторами, если нужно)

2024-06-12 11:46 UTC, Ankhena commented on source/form.html
> +                  кота</h3></legend>
```suggestion
              <legend class="visually-hidden">Персональные данные
                  кота</legend>
```

Заголовки филдсетов это legend

2024-06-12 11:46 UTC, Ankhena commented on source/form.html
> +              <label for="questionary__name">Имя<sup>*</sup></label>
```suggestion
              <label for="questionary__name">Имя*</label>
```
Нельзя использовать теги просто так, они должны соответствовать семантике. Звездочка это не верхний индекс, даже если дизайнер её нарисовал чуть повыше основного текста. 
Если обертка нужна исключительно для стилизации, то span

2024-06-12 11:46 UTC, Ankhena commented on source/form.html
> +              <br>
```suggestion
              
```

2024-06-12 11:46 UTC, Ankhena commented on source/form.html
> +              <label for="ongoings"></label>
Пустой label не имеет смысла, нужно дописать текст

2024-06-12 11:46 UTC, Ankhena commented on source/form.html
> +                id="ongoings">расскажите обо всех повадках кота</textarea>
```suggestion
              <textarea name="text"
                id="ongoings" placeholder="Расскажите обо всех повадках кота"></textarea>
```

2024-06-14 06:31 UTC, Roman3723 commented on source/index.html
> +        <a class="main-header__logo-text" href="#">
согласен, что логотип - блок. Но при этом он имеет значительные модификации - в хедере изображение-ссылка + текст-ссылка (и при этом с разной шириной между элементами у каждой из трех версий диагонали), в футере - только текстовый вариант. Я бы рад переиспользовать его, но пока что сложно понять логику реализации такого составного лого - оба ли элемента должны иметь независимые ссылки, или они оба входят в общую кликабельную область. Таким же образом мне была (и осталась) не понятной ситуация, когда, к примеру, карточка товара имеет текст-ссылку и изображение товара тоже - ссылка. Я бы вынес эту тему на созвон, потому что действительно хочется разобраться

2024-06-14 08:18 UTC, Roman3723 commented on source/index.html
> +          <input class="burger-checkbox" type="checkbox" id="burger-checkbox">
Способ конструирования кнопки нашел на просторах сети, там предлагался вариант с инпутом, который в дальнейшем должен быть скрыт (например, здесь - [htmlbook.ru](https://htmlbook.ru/blog/menyayushcheesya-gamburger-menyu-na-css)). За последние дни посмотрел много видео по теме и вижу, что можно без этого шага вполне обойтись, но все равно поскольку к css прибегнуть в задании нельзя - кнопку тоже не сверстать, так что я пока в раздумьях - как обозначить местонахождение будущей бургер-кнопки. Буду рад обсудить в чате.

2024-06-14 08:22 UTC, Roman3723 commented on source/index.html
> +            <!--! Q не блокирует ли враппер действие кнопки бургер на список меню?-->
уже сейчас понимаю, что он лишний. Мысль была в том, что список навигации все равно скорее всего в обертке, чтобы назначать ему флекс-свойства. Я не понимал на момент написания кода как реализуется меню в виде вертикального списка в моб версии и думал что для этого нужен специальный класс будет. Сейчас понял, что есть некий медиазапрос с заданной для него шириной экрана (а может и еще какое-то свойство), которое при изменении ширины и бургер скрывает, и список из горизонтального делает вертикальным. Спасибо ютубу, но без рук это все в голове долго не живет

2024-06-14 09:36 UTC, Roman3723 commented on source/index.html
> +                <a href="#">главная</a>
на первом курсе учили оставлять заглушку, если находишься на активной странице. Ведь переход по ссылке в таком случае не нужен. А на спринте узнал, что лого-ссылка главной страницы оформляется на практике как спан с картинкой, а не ссылка с заглушкой. Сейчас посмотрел - в моем первом учебном проекте лого на странице индекс оформлено как <a> с изображением внутри, но без атрибута href. интересно, ошибка ли это?

2024-06-14 10:02 UTC, Roman3723 commented on source/index.html
> +              <li class="list__item"><a href="form.html">
то есть, доводить руками все ситуации, если вложенная в <li> ссылка или <p> осталась на той же строчке?

2024-06-14 10:05 UTC, Roman3723 commented on source/index.html
> +        <a class="hero__button button--green" href="#">подобрать программу</a>
Согласен, визуально двойной дефис куда удобнее! Но сам БЭМ-валидатор не воспринимает ли его использование как ошибку?

2024-06-18 11:44 UTC, Roman3723 commented on source/index.html
> +            вес.</p>
Памятуя как раз строгость Pixel Perfect'а я сразу застолбил места для переносов для визуального соответствия мобильной версии, чтобы на этом этапе не вспоминать о других способах переноса текста. Сейчас убираю.

2024-06-18 12:58 UTC, Roman3723 commented on source/form.html
> +              <label for="questionary__name">Имя<sup>*</sup></label>
Не согласен. Звездочка смотрится как верхний индекс и похожий пример есть в демке Барбершопа
![1 sup](https://github.com/htmlacademy-adaptive/2426581-cat-energy-1/assets/148534470/cb54c6c8-ec5c-4dc6-b83e-b429c5ac35cb)

2024-06-19 16:28 UTC, Roman3723 commented on source/index.html
> +        <div class="stats__wrapper slider">
Тема слайдеров на первом курсе была одной из самых не усвоенных. В демке этого курса во всех случаях, где в секции есть слайдер - он прописан в имени класса в начале секции, а не именно в месте, где будет реально расположен. Поэтому написал так.

2024-06-20 13:01 UTC, Roman3723 commented on source/index.html
> +        <div class="main-footer__copyright copyright">
Список выше - ладно, но копирайт на секцию не тянет. Да будет span

2024-06-24 08:47 UTC, Ankhena requested changes

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
> +        <h2 class="hero__title">Функциональное питание&nbsp;для котов</h2>
Предлоги не должны оставаться висячими. Сейчас ты склеил предлог с предыдущим словом и он останется висящим. А должно быть наоборот.

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
> +              <a href="#">Главная</a>
Осталась решетка. 
Модификатор лучше вешать на ссылку, а не на li. Ведь это она ведет на текущую страницу (или какие-то другие нюансы)

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
> +        <h2 class="hero__title">Функциональное питание&nbsp;для котов</h2>
Я бы, кстати, делала это h1 и не выдумывала бы лишнего.

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
> +              вес.</p>
Неразрывные пробелы нельзя ставить просто так. Они ставятся по определенным правилам типографики. Можно пользоваться специальными сервисами. 
Нет никакого оправдания неразрывному пробелу между словами "питомцу" и "сбросить". Между "Energy" и "Slim" тоже. И тут `почти&nbsp;утратил`.

И всюду по текстам аналогично.

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
>            <ul class="usage__list">
Кажется, заголовок не попал в div. 
В композиции, как сейчас, div вообще не нужен. А вот если заголовок будет внутри, то нужен, потому что будет центровщиком.

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
> +          <div class="example-report">
По возможности нигде не должно быть обертки для dl. Потому что зачем бы она?

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
> +              <dd>Затрачено времени</dd>
Расскажи, пожалуйста, кто тут термин, а кто значение?

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
> +          дилеров!</b>
Точно не `b`. 
`b`  это кусок фразы, который нужно чем-то выделить. Обычно спаном. 
А у нас тут целая фраза. 
Так что либо `p` либо `h2`.

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
>          </span>
Я бы оставила ссылкой. Хотят кликать - пусть себе кликают.

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
> +                <!--здесь будет свг-->
не будет ;)
Здесь будет псевдоэлемент в стилях

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
> +              <span class="visually-hidden">мы во VKontakte</span>
Нет такого слова

2024-06-24 08:47 UTC, Ankhena commented on source/index.html
> +        <span class="footer__copyright copyright">
Тут сложная логика
1. `div` был лучше чем `span`, ведь это целый блок, а не часть фразы.
2. По спецификации `div` можно использовать тогда, когда нет более подходящих по смыслу тегов. Тут определенно есть `p`.
3. Эта обертка вообще не нужна. 

p.s. и это не копирайт. "Копирайт" принадлежит заказчику и пишется вовсе не так. 
Академия - это разработчик сайта. Developer. 

Вот прям сейчас, при обучении, конечно, права у Академии. Но мы будем считать, что делаем настоящий сайт и тебе же будет гораздо удобнее, если ты сможешь переиспользовать созданные прямо на обучении блоки в реальных проектах. Просто возьмешь этот, изменишь стиль и текст и получишь готовый блок, затратив на это минимум времени и не изобретая новый.

2024-07-04 13:31 UTC, merged